---
name: "AudioMuse AI"
guid: "e3831be1-c025-4ebc-bc79-121ad0dfc4e1"
version: "1.0.0.0"
targetAbi: "10.7.7"
framework: "net6.0"
overview: "Integrates Jellyfin with an AudioMuse AI backend."
description: >
  Integrates Jellyfin with an AudioMuse AI backend.
  This plugin provides connectivity between your Jellyfin server and an external AI-powered music analysis or recommendation service.
category: "Metadata"
owner: "neptunehub"
artifacts:
  - "Jellyfin.Plugin.AudioMuseAi.dll"
changelog: >
  Initial release of the AudioMuse AI plugin.
